-- Swap the random picsum photos for the on-brand placeholder jackets generated by
-- scripts/generate-covers.mjs. Random landscape photography made a bookshop look like
-- a travel blog. These are still placeholders — replace with real photography by
-- updating product_images.url, no code change needed.
update public.product_images pi
set url = '/covers/' || p.slug || '.svg',
    alt = p.title
from public.products p
where pi.product_id = p.id
  and pi.url like 'https://picsum.photos/%';
